### ISSUE TITLE
Argument 'grplab' contains one or more fields which are not character datatype.

### ISSUE THREAD

**Issue by cgraham13** [royfrancis/pophelper#11]
I am having some issues trying to add the group label panel to my image. I have 141 individuals in my analysis and have created a file with 141 rows corresponding to the population they are from. When I try to read in the file into grplab I get the following error:

Error in verifyGrplab(grplab) : 
  verifyGrplab: Argument 'grplab' contains one or more fields which are not character datatype.

This is the script I am using:

pop.labels <- read.table("20Xm3M1n1r30-poplabels.txt")

plotQ(Q.data, 
      clustercol = c("lightblue", "purple"),
      #useindlab = T,
      showindlab = T,
      grplab = pop.labels,
        #this needs to be a data.frame, each label set must be a character vector 
      showlegend = F,
      showsp = T,
      splab = "20Xm3M1n1r30Neutral \n K2",
      splabsize = 3
      )

Thanks!

Carly

**Comment by royfrancis** [comment]
I suspect the issue is here:

`pop.labels <- read.table("20Xm3M1n1r30-poplabels.txt")`

`read.table()` and `read.delim()` by default converts character columns to factors. If you change it to below, the character columns will remain as characters.

`pop.labels <- read.table("20Xm3M1n1r30-poplabels.txt",stringsAsFactors=FALSE)`

**Comment by cgraham13** [comment]
That solved it, thanks Roy!!
