### ISSUE TITLE
Aligning plots with varying numbers of individuals

### ISSUE THREAD

**Issue by ashaff4** [royfrancis/pophelper#22]
Hi there,

I'm trying to create an "A", "B", and "C" figure with my three structure plots. Each plot has a different number of individuals (97, 55, and 46). When the plots are generated, they are all the same dimensions, but the width of the individual bars are all different sizes (smaller width for larger _n_ and larger width for smaller _n_).  I am trying to get each plot to have matching barsizes. I tried adjusting "barsize" but that left the entire plot the same dimension and only increased or decreased the amount of space between the bars. I generated each as a plotQmultiline. Is there another way to accomplish this? Thank you!

**Comment by royfrancis** [comment]
What you described is the expected behaviour. If you want equal barwidth, and differing figure width, you just have to adjust the width of each plot separately. 

For example, say one bar is 0.05cm,
create one plot for 97 indiv with a width of  (97x0.05cm) = 4.85cm
create one plot for 55 indiv with a width of  (55x0.05cm) = 2.75cm
create one plot for 46 indiv with a width of  (46x0.05cm) = 2.30cm

This should give you 3 plot of varying widths but more or less equal bar width.

**Comment by ashaff4** [comment]
Thank you so much! It seems so obvious now...

Thanks for your quick feedback!
