### ISSUE TITLE
re-ordering groups over multiple label sets

### ISSUE THREAD

**Issue by SueFrei** [royfrancis/pophelper#31]
Hi,
Thanks for making pophelper available. I have plotted my admixture results with multiple label sets, Pop (population names) and Ancient/Modern. My input files list the populations in alphabetical order.  I re-ordered my groups into contiguous blocks according to Ancient/Modern. Sortind is set to 'all'. However, I would also like to re-order the Pop groups within the blocks of Ancient and Modern. Instead of alphabetical order, I would like to order them according to similarity of admixture proportions. I'm not clear how I could achieve this either automated or manually. Would it be best to drop the ordering by ancient/modern and just re-order the pops somehow by similarity, or is there a way to manually state the order of all the pops that I would like the plot to be in? Could it be done by changing the individual labels and sorting by that somehow?
Thanks for any advice,
Suzanne

**Comment by royfrancis** [comment]
I could explain this in a convoluted way, but it's probably easier if you provide me with one run file and the label file.

**Comment by royfrancis** [comment]
Make sure you are using the latest version of pophelper. The V2 group label column was individual labels rather than group labels, so that was not used.

```r
library(pophelper)

# read data
alist <- readQ(files="test_Admixture.8.Q.txt")
labels <- read.csv("test_poplabels.txt", header=F, stringsAsFactors=F, sep = "\t")

# groups order by V3 and then by V1
qdata1 <- plotQ(alist,grplab=labels[,c(1,3)],ordergrp=T,selgrp="V3",
               splabsize=8,grplabangle=90,grplabpos=0.6,,grplabheight=1,grplabjust=1,
               panelratio=c(2,2),height=8,outputfilename="figure1",returndata=T)
```

![figure1](https://user-images.githubusercontent.com/5083500/40686867-0d81fa80-6399-11e8-9ed4-0a627e310c2a.png)

The samples are ordered by group labels V3 and then by V1. This is done by setting `ordergrp=T` and `selgrp="V3"`. More importantly, the resulting order of data and labels are saved to `qdata1`.

In the next step, we use the saved data, set `ordergrp=F` since we don't need ordering of group labels. Now we use `sortind="all"` to sort individuals within groups set by `selgrp="V3"`.

```r
# Within V3, ind sorted by 'all'
qdata2 <- plotQ(qdata1$data$qlist,grplab=qdata1$data$grplab[[1]],ordergrp=F,selgrp="V3",sortind="all",
               splabsize=8,grplabangle=90,grplabpos=0.6,grplabheight=1,grplabjust=1,
               panelratio=c(2,2),height=8,outputfilename="figure2",returndata=T)
```

![figure2](https://user-images.githubusercontent.com/5083500/40687039-a3f30a54-6399-11e8-9be9-34a0b68e0a44.png)

V1 labels are still too many to be legible. It might be better to group them further and also shorten the labels. The output is again saved to `qdata2`.

Some other ideas. You could use V2 labels as individual labels. And plot again creating a wider plot and decreasing group label size.

```r
# add ind labels back to returned dataframe manually.
rownames(qdata1$data$qlist[[1]]) <- labels$V2[as.numeric(rownames(qdata1$data$grplab[[1]]))]

# showing ind labels, increased width
plotQ(qdata1$data$qlist,grplab=qdata1$data$grplab[[1]],ordergrp=F,selgrp="V3",sortind="all",
      splabsize=8,grplabangle=90,grplabpos=0.6,grplabsize=2,grplabheight=1,grplabjust=1,
      useindlab=T,showindlab=T,
      panelratio=c(2,2),height=12,width=60,outputfilename="figure3")
```

![figure3](https://user-images.githubusercontent.com/5083500/40687137-ea2ca278-6399-11e8-9a2b-38887abafa51.png)

It doesn't really make a big difference. It's still hard to read. 

The data we previously saved to `qdata2` can be exported out as a text file. Maybe, it's easier to see as a table.

```r
# write data as text file
write.table(cbind(qdata2$data$qlist[[1]],qdata2$data$grplab[[1]]),
            "arranged.txt",sep="\t",quote=F,row.names=F)
```

It can also be directly exported to Excel. Then conditional formatting can be used to colour clusters and individuals can be identified (See attached Excel file below).

```r
# export as excel (requires java)
library(xlsx)
write.xlsx2(x=cbind(qdata2$data$qlist[[1]],qdata2$data$grplab[[1]]),
file="arranged.xlsx",sheetName="arranged")
```

[arranged.xlsx](https://github.com/royfrancis/pophelper/files/2051202/arranged.xlsx)

Note that column1 (row labels) reflect original sorting order. Can be useful. Also, perhaps it's a good idea to consolidate and decrease V1 labels further.

**Comment by SueFrei** [comment]
Dear Roy,
This is excellent and really clear, thank you for your time and effort. I am trying this out on my computer. I can try using more regional labels. I am thinking of ways I could maintain the population groups (V1) so that for example all Anatolian_N individuals remain together (and have a single label showing for all of them) and appear next to another population that for instance has a similar major component (although still keeping ancient and modern separate). I can think of possibly manually manipulating the text file but wonder if there are some other options?

**Comment by royfrancis** [comment]
I think some level of manual curation will be necessary sooner or later on V1 labels. It's a bit too messy and inconsistent. I think it might not be able to show all the labelling in one figure. It will be unreadable. You might have to create multiple plots. Create multiple levels of labels. For example, lev1 labels goes like Central Europe, Norther Europe, Mediterranian, Middle east, Central Asia etc.. Lev2 labels could be below this, maybe countries... Lev 3 could be perhaps regions in the countries..

Then you could have one overview plot with lev 1 labels. Then create separate plots to highlight certain areas using lev 2 labels. More finer plots with lev 3 labels perhaps. This is just an idea. here is an example:

https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12862-015-0392-3/MediaObjects/12862_2015_392_Fig8_HTML.gif
