### ISSUE TITLE
different delta K from Structure Harvester vs pophelper

### ISSUE THREAD

**Issue by tommydevitt** [royfrancis/pophelper#33]
I just noticed that I get a different value for the Evanno et al statistic (delta K) when using Structure Harvester vs. pophelper. Are you calculating delta K the same way as Structure Harvester?

**Comment by royfrancis** [comment]
From what I've seen, they should give the same results. If you think you get different results, you are welcome to send me some sample files and I can look into it.

**Comment by tommydevitt** [comment]
OK. Should I email them or attach here?

**Comment by royfrancis** [comment]
You can attach them here.

**Comment by tommydevitt** [comment]
[sosorum-min130_Harvester_Upload.zip](https://github.com/royfrancis/pophelper/files/2246596/sosorum-min130_Harvester_Upload.zip)

**Comment by royfrancis** [comment]
You have runs of different number of individuals and different loci. So I separated them into two groups: sim and sosorum. And the sosrum set has non-sequential K, ie; you have k1 followed by 5,6,7 etc. So, I removed k1.

Then I tested the files on Structure Harvester and pophelper. I took some quick screenshots of the results.

See sim dataset (Left: SH, Right: pophelper)

![screenshot 2018-07-31 20 34 30](https://user-images.githubusercontent.com/5083500/43479911-fa9b7fc8-9501-11e8-9016-b1e91221a0ed.png)

And here is sosrum dataset (Left: SH, Right: pophelper)

![screenshot 2018-07-31 20 35 24](https://user-images.githubusercontent.com/5083500/43479929-0590a372-9502-11e8-857d-06a226feda6a.png)

You can ignore the deviations for derivatives that pophelper reports, because Structure Harvester does not compute that. Other than that, pophelper and Structure Harvester gives the same results.

**Comment by tommydevitt** [comment]
My mistake, sorry for the trouble. And thanks for checking so quickly.
