### ISSUE TITLE
collect clumpp output not working

### ISSUE THREAD

**Issue by subha-sorghum** [royfrancis/pophelper#46]
i am new to STRUCTURE and pophelper. I am running my test result data from STRUCTURE output. Everything is working fine with pophelper other than the function collectClumppOutput().. The part of the script is as follows:

collectClumppOutput(prefix = "pop", 
                    #filetype = "",
                    runsdir = NA, 
                    newdir = NA, 
                    quiet = FALSE) 

There is no error message but this following message:

No suitable file found in directory: pop_K10
No suitable file found in directory: pop_K2
No suitable file found in directory: pop_K3
No suitable file found in directory: pop_K4
No suitable file found in directory: pop_K5
No suitable file found in directory: pop_K6
No suitable file found in directory: pop_K7
No suitable file found in directory: pop_K8
No suitable file found in directory: pop_K9
Directories processed: 0
Files copied: 0
[1] 0 0

I have also uploaded my input data (results from structure) and my entire script.

I am not sure if it is a problem of the code or my files.

Thank you very much.

[Pophelper.txt](https://github.com/royfrancis/pophelper/files/3300586/Pophelper.txt)
[results_job_f.zip](https://github.com/royfrancis/pophelper/files/3300591/results_job_f.zip)

**Comment by royfrancis** [comment]
Based on your script, there are no output results from CLUMPP, therefore, `collectClumppOutput()` has nothing to work on.

In this step `clumppExport(qlist=slist, useexe=FALSE)`, you can set `useexe=TRUE` like `clumppExport(qlist=slist, useexe=TRUE)`. For your case, would recommend `clumppExport(qlist=slist, useexe=TRUE,parammode=3)` since you have a lot of loci and lot of samples. 

Alternatively, (or if `useexe` doesn't work for you) you can download the CLUMPP executable and execute it manually in each of the `clumppExport()` folders.

**Comment by royfrancis** [comment]
In the latest version v2.3.0, you don't need to use CLUMPP, you can use `alignK()` to align clusters.
