### ISSUE TITLE
 Error: Duplicated contiguous block of grp labels. Not possible to subset or reorder grps.

### ISSUE THREAD

**Issue by HeatherKates** [royfrancis/pophelper#5]
Hello,

when I use group labels and attempt to reorder my samples by group, 
I get the error
 Error in pophelper:::grpLabels(df = df1, grplab = grplab[[pp]], subsetgrp = subsetgrp,  : 
  grpLabels: Duplicated contiguous block of grp labels. Not possible to subset or reorder grps.

The format of my group labels text file is like:
1 A
2 A
3 B
4 B
5 C
6 C
7 A

And the format of my ind labels file is like:
1 A_ind1
2 A_ind2
3 B_ind3
4 B_ind4
5 C_ind5
6 C_ind6
7 A_ind7

The problem seems to be because population A occurs in two different parts of the group labels vector, but because of the original order of the samples in the STRUCTURE output files, I can't figure out any other way to order the group label vector. (i.e. in this example, the 7th sample in my STRUCTURE files needs to have the same group label as samples 1-2).

I see in the code that the error is caused because
if(length(rlegrp$values) != length(unique(rlegrp$values)))

but I don't understand the rle() function enough to interpret this
R code and example input files attached

[issue.zip](https://github.com/royfrancis/pophelper/files/974272/issue.zip)

**Comment by royfrancis** [comment]
The error is as expected because there is non-contiguous grouping. As of now, the function is not designed to regroup. The labels are expected to be grouped together on input. I will fix this at some point.

The solution is to add the labels to your qlist dataframes, order the dataframe based on labels and remove the labels. Then use the newly ordered qlist object and labels.

I have modified just the loop part of your code.

```r
# Generate barplots for CLUMPP output files
for (i in 1:18){
  rownames(qlist2[[i]]) <- inds$Label
  # add labels to df
  qlist2[[i]]$label <- grp$V2
  # order df based on labels
  qlist2[[i]] <- qlist2[[i]][order(qlist2[[i]]$label),]
  # get new order of labels
  labs <- qlist2[[i]]$label
  # remove label column
  qlist2[[i]]$label <- NULL
  # use new order of data and new order of labels
  plotQ(qlist2[i],useindlab=T,grplab=list("lab1"=labs),sp=F,subsetgrp=c("Wild","Landrace","Improved"))
}
```
![pop_k2-combined-aligned-1](https://cloud.githubusercontent.com/assets/5083500/25677854/e929a686-3047-11e7-8333-164cb99c196c.png)

I noticed that you using `useindlab=T` for plotting. This will have an effect on the order of individuals only when using `sortind="label"`. Just so you know.

**Comment by royfrancis** [comment]
Additional argument `ordergrp` to reorder group labels added in v2.2.0.
