### ISSUE TITLE
Repeated sampling analysis

### ISSUE THREAD

**Issue by Nofinter-oss** [royfrancis/pophelper#53]
Hello, I like this package so much! I want to know how to repeat sampling analysis like CLUMPP.Hope you can answer my issue! Thank you very much!

**Comment by royfrancis** [comment]
Hi, Sorry, I seem to have missed your question. I am not entirely sure what you mean. 

CLUMPP doesn't do repeat analysis as such. If you mean multiple runs of admixture estimates, that is produced by tools like STRUCTURE, ADMIXTURE etc. You get many runs from them for each value of K. Now I refer to them as repeats for each K. What happens with each repeat is that the admixture values get assigned to a random cluster. ie; a cluster named Cluster1 in repeat1 may be called Cluster4 in repeat2. What CLUMPP does is to correct these labels. So that if there are 4 repeats, Cluster1 will be Cluster1 across all four repeats.
