### ISSUE TITLE
y-axis label

### ISSUE THREAD

**Issue by kpboh** [royfrancis/pophelper#6]
Thanks very much for this helpful tool! Two enhancements that I think might make it even better:

1. Adding ability to enable y-axis w/ label ("proportion ancestry") and controls for ticks. Seems like this could be easily accomplished via ggplot?
2. Add ability to plot lines separating the individual samples (similar to the dashed lines that can currently be used to separate groups). For some reason, simply modifying the barsize= value does not seem to produce reliable results.

Cheers!

**Comment by royfrancis** [comment]
Hi Kevin, Thanks for the suggestions. 
1. So y-axis labels and ticks. I never really understood why it's useful. It is a constant and always goes from 0 to 1. Since the bars are stacked and it's proportion, even the order (top-bottom or bottom-top) of the y-axis does not matter. It clutters and uses up space. I would like to hear a good argument for having them. Anyway, you mean y-axis options for `plotQ()` right, because `plotQMultiline()` already has options for turning on y-axis and ticks.
2. Good idea. I could add borders to bars and that would help with this issue.

**Comment by kpboh** [comment]
Thanks for the quick reply! And yeah, I see your point. I just know that some reviewers/editors (and research advisers!) have been known to balk at seeing bivariate plots with an unlabeled axis label. But on the other hand, we generally don't ask for 'axes' on pie charts, which seem to function in an equivalent role... 

And thanks for considering the individual sample borders. I've seen many recent examples with large genomic SNP datasets where there is very little, if any, admixture, resulting in rather boring single-color blocks. In such plots, the number of samples is hard to discern without some type of line separate samples.

Thanks again!

**Comment by royfrancis** [comment]
Arguments `barbordersize` and `barbordercolour` added in version `2.2.1`.

**Comment by royfrancis** [comment]
Arguments `showyaxis` added to `plotQ()` in version `2.2.4`.
